version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kbridh-template
    volumes:
      - kbridh-template-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    volumes:
      - kbridh-template-redis:/data
volumes:
  kbridh-template-pgdata:
  kbridh-template-redis:
